# Generated by Django 3.0.4 on 2020-03-20 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdditionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_query_name='userinfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
