# Generated by Django 3.0.4 on 2020-04-01 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200401_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useradditioninfo',
            old_name='user_department',
            new_name='department',
        ),
    ]
