# Generated by Django 3.0.4 on 2020-04-01 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_department_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_query_name='userdep', to=settings.AUTH_USER_MODEL),
        ),
    ]
