# Generated by Django 3.0.4 on 2020-04-01 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200401_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='user',
        ),
    ]
